can add product types
nss-day-cohort-60/ye-old-taco-bell-labs pull request #15
Opened 2023-01-13 16:02 UTC by sydneyrd

Closes #7

#Description
Added create_product_type in product type view, added create product type to do_post

#Steps to test
Pull the sydney-add-product-type and switch to it
Start the API in debug mode
Open Postman and Post a product type 
   {
        "id": 4,
        "description": "test me"
    }
http://localhost:8088/product_types
Verify that you get a single dictionary back.
GET all product types and make sure the new type has been added

2023-01-13 16:11 UTC, stevebrownlee requested changes

2023-01-13 16:11 UTC, stevebrownlee commented on request_handler.py
> +            new_post = create_product_type(post_body)
You are sending the request body to the creation function without doing any validation. This is one of the acceptance criteria in the #7 ticket. Please validate that the description property is in the request body before attempting to add to the list.

2023-01-13 16:11 UTC, stevebrownlee commented on views/product_type_view.py
> +    product_type["id"] = new_id
Would you consider combining these two operations into 1?

```py
product_type['id'] = max_id + 1
```

I don't believe that reduces the readability of the code.

2023-01-18 15:06 UTC, sydneyrd commented on views/product_type_view.py
> +    product_type["id"] = new_id
Yeah that looks better

2023-01-18 15:30 UTC, sydneyrd commented on request_handler.py
> +            new_post = create_product_type(post_body)
Yep I fixed it!

2023-01-18 15:36 UTC, stevebrownlee approved these changes
Thanks for making the requested changes. Functionality works as expected.

2023-01-18 15:36 UTC, merged